In [1]:
import numpy as np

In [2]:
data1= [1,2,3,4,5]
arr1 = np.array(data1)
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [6]:
print(arr1.ndim)

1


In [7]:
print(arr1.dtype)

int64


In [8]:
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr1.dtype)

int64


In [10]:
print(arr2.ndim)

2


In [11]:
print(arr2.shape)

(2, 3)


In [12]:
arr3= np.ones((2,3))

In [13]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr4 = np.zeros((3,4))

In [15]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr5= np.eye(4)

In [17]:
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
arr6 = np.random.rand(2,3)

In [19]:
arr6

array([[0.00306733, 0.46018674, 0.13912318],
       [0.43545143, 0.49564142, 0.6419486 ]])

In [20]:
arr7 = np.random.randint(1,10,(3,4))

In [21]:
arr7

array([[9, 7, 4, 2],
       [7, 9, 1, 6],
       [9, 5, 7, 6]])

In [22]:
arr8= np.arange(0,10,2)

In [23]:
arr8

array([0, 2, 4, 6, 8])

In [26]:
print(arr7 * arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
print(arr7 - arr4)

[[9. 7. 4. 2.]
 [7. 9. 1. 6.]
 [9. 5. 7. 6.]]


# Indexing and Slicing in NumPy

In [29]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
arr[5]

np.int64(5)

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
arr2d[2]

array([7, 8, 9])